[package]
name = "bloom_filter"
version = "0.1.0"
edition = "2021"
authors = ["Jude Muriithi <jkmuriithi11@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
